remote_theme: kerim/jekyll-serif-theme

title: "Kerim's Digital Garden"
description: Growing ideas
baseurl: 'http://kerim.oxus.net/digitalgarden'

footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'
    

