remote_theme: kerim/moving

# Site settings
title:       Kerim's Digital Garden
email:       kerim.mail@oxus.net
author:      Kerim Friedman
description: "Growing ideas since 2021."
url:         "https://kerim.oxus.net/digitalgarden/"

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://i.loli.net/2019/08/26/JzCLhDWPEybZr2T.jpg" # avatar in about page
  about_you: a short description about you. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.


