remote_theme: kerim/jekyll-serif-theme

title: "Kerim's Digital Garden"
description: Growing ideas
baseurl: '/digitalgarden/'


homepage:
  show_call_box: false

footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'
    

